// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJvIlaExpFL8UIpUdnWAZ-RHJPFj_h6fQ',
    appId: '1:464505216191:web:37f30ea5ff95d4a493fa0a',
    messagingSenderId: '464505216191',
    projectId: 'evently-app-train',
    authDomain: 'evently-app-train.firebaseapp.com',
    storageBucket: 'evently-app-train.firebasestorage.app',
    measurementId: 'G-T4Q7HGX4EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsxaguK8F-sF5smIPOjwBNqJfSMXZ87MA',
    appId: '1:464505216191:android:630df05396ca237a93fa0a',
    messagingSenderId: '464505216191',
    projectId: 'evently-app-train',
    storageBucket: 'evently-app-train.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeOTsKPIVBFXbcOxiby691Ec6-nAyDw9Y',
    appId: '1:464505216191:ios:b8d673875e2722de93fa0a',
    messagingSenderId: '464505216191',
    projectId: 'evently-app-train',
    storageBucket: 'evently-app-train.firebasestorage.app',
    iosBundleId: 'com.example.eventlyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeOTsKPIVBFXbcOxiby691Ec6-nAyDw9Y',
    appId: '1:464505216191:ios:b8d673875e2722de93fa0a',
    messagingSenderId: '464505216191',
    projectId: 'evently-app-train',
    storageBucket: 'evently-app-train.firebasestorage.app',
    iosBundleId: 'com.example.eventlyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJvIlaExpFL8UIpUdnWAZ-RHJPFj_h6fQ',
    appId: '1:464505216191:web:f55beb9d6ef57f1093fa0a',
    messagingSenderId: '464505216191',
    projectId: 'evently-app-train',
    authDomain: 'evently-app-train.firebaseapp.com',
    storageBucket: 'evently-app-train.firebasestorage.app',
    measurementId: 'G-Y4XMGXCRTR',
  );
}
